Send client updates on schedule change
venueless/venueless pull request #267
Opened 2021-08-15 14:57 UTC by rixx

2021-08-15 16:58 UTC, raphaelm requested changes
I have one API design concern, see inline. Another reason for that concern is that having a separate URL decouples it a little from the rest of the REST API, which is currently unused and might require some kind of rewrite if we ever need it more often. Such a thing will be easier if we don't mix views in weird ways already. Otherwise :+1:

2021-08-15 16:58 UTC, raphaelm commented on server/venueless/api/views.py
> +            - schedule_update
Any reason for not just creating another `APIView` with its own URL? Would feel much cleaner.

2021-08-15 19:29 UTC, rixx commented
Hm, yeah, I was torn on where to put this in the existing REST API. My intuition was to just add an action to the existing world viewset. When I discovered that /world doesn't use a viewset, I just tried to re-use as much code as possible (it's not trivial to just add a detail URL to an APIView).

I guess I'll write a single method and route it at `/world/{slug}/update_schedule`, then?

2021-08-18 17:20 UTC, raphaelm approved these changes

2021-08-18 18:09 UTC, rashfael approved these changes

2021-08-18 18:11 UTC, merged